apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: golang
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    app: golang

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: golang
  name: golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
      - image: docker.io/library/golang-project:latest
        name: golang
        imagePullPolicy: Never
        ports:
          - containerPort: 8000
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: database
