apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: golang
  name: golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
      - image: golang-project:latest
        name: golang